<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City, state, or zip code_jobs-search-box-location-id-ember606</name>
   <tag></tag>
   <elementGuidId>57bd6071-1e58-49ec-8ebe-5f7933d46ccd</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'jobs-search-box-location-id-ember606' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobs-search-box-location-id-ember606']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jobs-search-box-location-id-ember606</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox[name=&quot;City, state, or zip code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>092c2eb0-80ff-487c-86c0-f5e8642cae19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobs-search-box-location-id-ember606</value>
      <webElementGuid>fb80104b-8bb5-4adc-afb5-6b3d70313cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jobs-search-box__text-input</value>
      <webElementGuid>7864f2c9-2c5a-41b3-9ed2-5555dd006dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-level2</value>
      <webElementGuid>7a391faa-c94e-4a0f-8480-0961941556d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f614a3dc-8210-43a3-88a5-cfe6b2c6c97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>0fa20091-f4ce-43ef-ba43-bb063b497b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>c760af1a-db80-4c45-8b39-28509ed5ee8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>cc1fe32e-0f6a-4505-895d-c139fc906dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>City, state, or zip code</value>
      <webElementGuid>5cc7f832-779e-4a16-b8f5-77a9474f5afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>50c7eec7-d4d5-471e-9645-b83a68f06514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43892dbe-1b7e-4139-ab7f-40837aa58d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-artdeco-is-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6ec5bcfe-4ffb-4ad7-b645-64dba20e37e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>triggered-expanded-ember610</value>
      <webElementGuid>dc22694d-cf73-4dca-90c4-47540280ddca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>triggered-expanded-ember610</value>
      <webElementGuid>27070bc4-47c3-40e9-9c93-8075cf1a0709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobs-search-box-location-id-ember606&quot;)</value>
      <webElementGuid>422edcd3-c278-4dc5-b46c-3682ff722c41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobs-search-box-location-id-ember606']</value>
      <webElementGuid>b2dc2306-cf26-4ae0-bc2e-f612524d755c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='location-typeahead-instance-ember606']/div[2]/input</value>
      <webElementGuid>c33a7a48-5c5c-4645-ae9d-e0a201d719c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e13677a7-6632-4ffb-ae67-5424bdf81f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jobs-search-box-location-id-ember606' and @type = 'text']</value>
      <webElementGuid>3eb75816-b183-4e03-a4e4-e309208434ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
