<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Easy Apply</name>
   <tag></tag>
   <elementGuidId>fa0e348a-139e-4d31-98be-1a297bb292bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='searchFilter_applyWithLinkedin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchFilter_applyWithLinkedin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Easy Apply filter.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9f921bbd-dbc5-4969-8f86-fc395d9af95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b270ea51-4261-4319-ab9e-fe172c608016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>685faae1-87e1-4403-89bb-dca4491bee4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Easy Apply filter.</value>
      <webElementGuid>349db865-2662-4927-9aa2-e27a45162250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchFilter_applyWithLinkedin</value>
      <webElementGuid>8c3eb2f0-eb5b-4b1b-8b5a-b10515407fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>artdeco-pill artdeco-pill--slate artdeco-pill--2 artdeco-pill--choice ember-view search-reusables__filter-pill-button</value>
      <webElementGuid>aaeb50c5-ad3b-430f-b92e-a9fb0314724f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1901e713-5d20-40c6-98c3-42d0c39e771d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-artdeco-is-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ac30edde-8cf3-4efc-a6e6-34544f9ae639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  
        Easy Apply
      
</value>
      <webElementGuid>842fe6ca-9768-4ee8-bbc1-4e67d116b197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchFilter_applyWithLinkedin&quot;)</value>
      <webElementGuid>311b0a6b-0ef8-4f7f-a29d-d65f2bba8b8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='searchFilter_applyWithLinkedin']</value>
      <webElementGuid>fe5ac25b-c386-4dda-8894-76e02ad50a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-reusables__filters-bar']/ul/li[7]/div/button</value>
      <webElementGuid>2c4f6ae5-fa4e-4bba-988f-bb99313a9eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Easy Apply']/parent::*</value>
      <webElementGuid>de6b26d2-f572-47ee-a76f-133044592f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[7]/div/button</value>
      <webElementGuid>376b1b81-1af1-4f01-ae2f-efdcd598162d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'searchFilter_applyWithLinkedin' and @type = 'button' and (text() = '  &#xd;
        Easy Apply&#xd;
      &#xd;
' or . = '  &#xd;
        Easy Apply&#xd;
      &#xd;
')]</value>
      <webElementGuid>15e471cf-e2e5-4e74-9cc6-c3cda856f904</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
