<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get started</name>
   <tag></tag>
   <elementGuidId>0aeea306-a3b2-4fa7-bc0f-bd700b5d2ddd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Get started&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b7ee56f-64a5-4638-92ff-840c11a4c373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ecb5f59-95e7-430f-8666-ce02cd6298f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex items-center justify-center text-foreground-250 fill-foreground-250 active:text-foreground-350 active:fill-foreground-350 dark:text-foreground-750 dark:fill-foreground-750 dark:active:text-foreground-650 dark:active:fill-foreground-650 shadow-button-strong-light dark:shadow-button-dark bg-stone-800 hover:bg-black active:bg-stone-750 dark:bg-slate-600 dark:hover:bg-slate-550 dark:active:bg-slate-600/80 text-base min-h-14 min-w-14 px-4 py-3.5 gap-x-3 rounded-4xl before:rounded-4xl before:absolute before:inset-0 before:pointer-events-none before:border before:border-transparent before:contrast-more:border-2 outline-2 outline-offset-1 focus-visible:z-[1] focus-visible:outline focus-visible:outline-stroke-900 w-full shadow-lg min-w-40 sm:w-auto</value>
      <webElementGuid>7a348b48-c205-4edc-8037-4fd44bb53f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Get started</value>
      <webElementGuid>f5df6ca6-6137-46ae-b01d-01f050ae11cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get started</value>
      <webElementGuid>21b4b1d6-da96-49e7-8145-f631c7b91a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/main[@class=&quot;relative overflow-hidden&quot;]/div[@class=&quot;h-dvh&quot;]/aside[@class=&quot;flex size-full flex-col overflow-auto px-6 pb-2 sm:pb-3&quot;]/div[@class=&quot;flex grow items-center justify-center pb-3&quot;]/div[@class=&quot;flex size-full flex-col&quot;]/div[@class=&quot;z-20 flex w-full flex-col items-center justify-center space-y-2&quot;]/button[@class=&quot;relative flex items-center justify-center text-foreground-250 fill-foreground-250 active:text-foreground-350 active:fill-foreground-350 dark:text-foreground-750 dark:fill-foreground-750 dark:active:text-foreground-650 dark:active:fill-foreground-650 shadow-button-strong-light dark:shadow-button-dark bg-stone-800 hover:bg-black active:bg-stone-750 dark:bg-slate-600 dark:hover:bg-slate-550 dark:active:bg-slate-600/80 text-base min-h-14 min-w-14 px-4 py-3.5 gap-x-3 rounded-4xl before:rounded-4xl before:absolute before:inset-0 before:pointer-events-none before:border before:border-transparent before:contrast-more:border-2 outline-2 outline-offset-1 focus-visible:z-[1] focus-visible:outline focus-visible:outline-stroke-900 w-full shadow-lg min-w-40 sm:w-auto&quot;]</value>
      <webElementGuid>eff34e79-5aa5-4e57-9d3d-5e428cb96800</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>725f5145-22c3-44f1-8976-3a884359fc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div[2]/aside/div/div/div[3]/button</value>
      <webElementGuid>0f8c39bb-db82-4503-8c26-7f04a93e583b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='companion'])[1]/following::button[1]</value>
      <webElementGuid>8402c5d9-de55-4dd5-a044-e08cc0d434ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AI'])[1]/following::button[1]</value>
      <webElementGuid>bd5f1de3-cc13-4293-881b-d499d0dd4536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/preceding::button[1]</value>
      <webElementGuid>0d8bad2e-fdbd-4b8e-ac7c-dd52871acdd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms'])[1]/preceding::button[1]</value>
      <webElementGuid>18bbac6f-13c7-4422-a78f-d29619ae75d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get started']/parent::*</value>
      <webElementGuid>19319e44-c5ff-4c38-873d-ec1654654dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>4672e716-52a9-4c55-8695-aaffd1f02b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Get started' and (text() = 'Get started' or . = 'Get started')]</value>
      <webElementGuid>d1f6c410-3b93-47c8-a496-b01f2b3b9a13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
