<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_hi_relative flex items-center justif_b4a0c3</name>
   <tag></tag>
   <elementGuidId>78abe5c1-dd56-4600-8378-7b1165dfb545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Submit message&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7166e677-3cc0-4bcf-8c81-cc0209c502b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8a44c68-4bbe-491e-8ea8-495dcdafce4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex items-center justify-center text-foreground-800 fill-foreground-800 active:text-foreground-600 active:fill-foreground-600 dark:active:text-foreground-650 dark:active:fill-foreground-650 bg-spot-peach-300 hover:bg-spot-peach-350 active:bg-spot-peach-250 dark:bg-slate-600 dark:hover:bg-slate-550 dark:active:bg-slate-600/80 text-xs size-9 rounded-xl before:rounded-xl before:absolute before:inset-0 before:pointer-events-none before:border before:border-transparent before:contrast-more:border-2 outline-2 outline-offset-1 focus-visible:z-[1] focus-visible:outline focus-visible:outline-stroke-900 rounded-submitButton</value>
      <webElementGuid>c14bbe8d-b137-4008-a7d2-51d2f0565cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Submit message</value>
      <webElementGuid>91cb0863-42fe-4cee-b622-1f75f7877412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Submit message</value>
      <webElementGuid>1f0ea40d-135e-4e7c-8d6c-16bfdc6bb9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/main[@class=&quot;relative overflow-hidden&quot;]/div[@class=&quot;pointer-events-none absolute bottom-0 flex w-full z-10&quot;]/div[@class=&quot;relative mb-4 flex w-full flex-col items-center px-3 sm:mb-8&quot;]/div[@class=&quot;relative max-h-full min-h-composer min-w-16 max-w-chat rounded-5xl&quot;]/div[@class=&quot;relative overflow-hidden backdrop-blur-2xl backdrop-saturate-200 before:bg-slate-200 before:opacity-40 dark:before:bg-midnight-800 dark:before:opacity-60 before:absolute before:inset-0 before:bg-blend-luminosity after:bg-spot-peach-100 after:opacity-60 dark:after:bg-slate-800 dark:after:opacity-50 after:absolute after:inset-0&quot;]/div[@class=&quot;pointer-events-auto relative flex flex-col contrast-more:border-2 z-10&quot;]/div[@class=&quot;relative flex max-h-full max-w-chat justify-center w-expanded-composer p-2 items-end&quot;]/div[@class=&quot;relative flex grow flex-col overflow-hidden bg-white/90 shadow-composer-input before:absolute before:inset-0 before:rounded-3xl before:border-2 before:border-stroke-350 dark:bg-midnight-900/80 dark:shadow-none w-auto contrast-more:border-2 ms-2 ms-2 before:opacity-0&quot;]/div[@class=&quot;flex grow items-end w-auto grow&quot;]/div[@class=&quot;relative bottom-0 my-1.5 flex h-9 items-center mx-1.5 w-auto gap-1&quot;]/div[1]/button[@class=&quot;relative flex items-center justify-center text-foreground-800 fill-foreground-800 active:text-foreground-600 active:fill-foreground-600 dark:active:text-foreground-650 dark:active:fill-foreground-650 bg-spot-peach-300 hover:bg-spot-peach-350 active:bg-spot-peach-250 dark:bg-slate-600 dark:hover:bg-slate-550 dark:active:bg-slate-600/80 text-xs size-9 rounded-xl before:rounded-xl before:absolute before:inset-0 before:pointer-events-none before:border before:border-transparent before:contrast-more:border-2 outline-2 outline-offset-1 focus-visible:z-[1] focus-visible:outline focus-visible:outline-stroke-900 rounded-submitButton&quot;]</value>
      <webElementGuid>b15028dd-f6b6-40f5-9904-25f64f30e967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>127c8fde-c3a5-43c1-89cb-a4f9c86bf2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div[3]/div[2]/div/div[2]/div/div/div[3]/div[2]/div[2]/div/button</value>
      <webElementGuid>4dc9b7a0-3a95-46bd-8718-e221924505a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hi'])[1]/following::button[1]</value>
      <webElementGuid>d645b9c3-4a15-4be7-817d-99298eb527bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message Copilot'])[1]/following::button[1]</value>
      <webElementGuid>afa5fef0-e2a9-4f29-8d75-f5ed8ab93b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>198d31a7-bc3c-4d13-8099-629dbcfb5ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Submit message']</value>
      <webElementGuid>0984c09f-3a58-4ea9-8c8d-c121418e9873</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
