<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Meadow</name>
   <tag></tag>
   <elementGuidId>fbf5934b-48f0-4c87-aacf-64d5655fa6a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Meadow&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a634fa46-4893-453c-835f-2cf96af15cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cda83f73-9022-4839-a3b3-afdb69b886d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shadow-none dark:shadow-none relative flex items-center justify-center text-sm min-h-10 min-w-10 px-3 py-2 gap-x-2 rounded-xl before:rounded-xl before:absolute before:inset-0 before:pointer-events-none before:border before:border-transparent before:contrast-more:border-2 outline-2 outline-offset-1 focus-visible:z-[1] focus-visible:outline focus-visible:outline-stroke-900 text-foreground-800 fill-foreground-800 active:text-foreground-600 active:fill-foreground-600 dark:active:text-foreground-650 dark:active:fill-foreground-650 bg-black/8 hover:bg-black/10 active:bg-black/5 dark:bg-white/8 dark:hover:bg-white/10 dark:active:bg-white/5 flex h-16 items-center justify-center</value>
      <webElementGuid>75ee417f-e330-43d5-a22d-4a2138f4f309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d2fca92b-f155-411f-b85a-954cabb6bbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Meadow</value>
      <webElementGuid>f25759fe-d557-453c-bb00-c0d1c9739b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/main[@class=&quot;relative overflow-hidden&quot;]/div[@class=&quot;h-dvh&quot;]/aside[@class=&quot;flex size-full flex-col overflow-auto px-6 pb-2 sm:pb-3&quot;]/div[@class=&quot;flex grow items-center justify-center pb-3&quot;]/div[@class=&quot;flex size-full flex-col&quot;]/div[@class=&quot;grow sm:grid sm:grid-rows-[1fr,auto,1fr] sm:pb-5&quot;]/div[@class=&quot;flex justify-center sm:items-end&quot;]/div[@class=&quot;grid grid-cols-2 gap-2 w-full sm:max-w-voiceSelector sm:rounded-4xl sm:bg-white/40 sm:p-3 sm:dark:bg-black/35&quot;]/button[@class=&quot;shadow-none dark:shadow-none relative flex items-center justify-center text-sm min-h-10 min-w-10 px-3 py-2 gap-x-2 rounded-xl before:rounded-xl before:absolute before:inset-0 before:pointer-events-none before:border before:border-transparent before:contrast-more:border-2 outline-2 outline-offset-1 focus-visible:z-[1] focus-visible:outline focus-visible:outline-stroke-900 text-foreground-800 fill-foreground-800 active:text-foreground-600 active:fill-foreground-600 dark:active:text-foreground-650 dark:active:fill-foreground-650 bg-black/8 hover:bg-black/10 active:bg-black/5 dark:bg-white/8 dark:hover:bg-white/10 dark:active:bg-white/5 flex h-16 items-center justify-center&quot;]</value>
      <webElementGuid>8f1c76d8-89cb-43e8-8eea-c2a644677aed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>bebef4a4-91fc-4bb6-832a-05713adf409d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div[2]/aside/div/div/div/div[3]/div/button[4]</value>
      <webElementGuid>9ae3f454-1f53-4adb-9ec0-e60996c21e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canyon'])[1]/following::button[1]</value>
      <webElementGuid>39552da3-7dda-4340-b165-fed6a75e14f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wave'])[1]/following::button[2]</value>
      <webElementGuid>43f42b63-c68c-4139-bbd1-6397ce491734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::button[1]</value>
      <webElementGuid>29c8610a-4f4a-47dc-9146-3f7371e25a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/preceding::button[2]</value>
      <webElementGuid>45841010-bdc4-45a5-ab2f-e9af9da4d5ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Meadow']/parent::*</value>
      <webElementGuid>6a8eba3f-55f3-40a7-bf81-f2ba598f4cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>d20d3e61-2833-4a97-a6f5-ccf4e13d486b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Meadow' or . = 'Meadow')]</value>
      <webElementGuid>00a0e0e7-1e9e-448a-ae14-a62865d33b77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
